### ISSUE TITLE
Req.user gives undefined

### ISSUE THREAD

**Issue by Ksathwik03** [woodburydev/passport-local-video#17]

**Comment by SanjeevYadavcr7** [comment]
Could you elaborate on that ?

**Comment by Ksathwik03** [comment]
I used the backend of this project as an authentication with react login and register works fine but when a user gets logged in and i try to check whether the user is logged in or not with req.user it always gives undefined even when the user is logged

**Comment by SanjeevYadavcr7** [comment]
Are you using passport.js for authentication ?

**Comment by naeemnh** [comment]
I am having the same issue. Essentially the /login and /register network requests returns a status of 200. The /user route returns `res.data` with an empty string/undefined. All of this using passport.js. My server code is uploaded [here](https://github.com/naeemnh/local-auth) for reference.

**Comment by SanjeevYadavcr7** [comment]
@naeemnh,  Is the user getting stored in your DB ?

**Comment by Ksathwik03** [comment]
> @naeemnh, Is the user getting stored in your DB ?

in my case the user got savd in Mongo db

**Comment by woodburydev** [comment]
You know to be honest, it sounds to me like if your code is completely identical to this github repository. That you are just not passing the cookie from the Front End, which is a common issue. Make sure that in all of your Axios requests you are making, you have  { withCredentials: true } inside the request.

example:
`const login = () => {
    Axios({
      method: "POST",
      data: {
        username: loginUsername,
        password: loginPassword,
      },
      withCredentials: true,
      url: "http://localhost:4000/login",
    }).then((res) => console.log(res));
  };`

**Comment by naeemnh** [comment]
@Ksathwik03, yes, the user is being saved in the Mongo db.
@woodburydev Thank you, got it fixed... `{ withCredentials: true }` was missing for me.
